
import java.util.Objects;

class Laptop
{
    String model;
    int price;

    // written
    // public String toString()
    // {
    //     return model +" : "+price;
    // }

    // generated by IDE
    @Override
    public String toString() {
        return "Laptop [model=" + model + ", price=" + price + "]";
    }

    // Dont use this code in Your program
    // public boolean equals(Laptop that)
    // {
    //     return this.model.equals(that.model) && this.price == that.price;
    // }
    // **** Above code is define correct for object comparision 
    // because Java: for equal Objct Value as well as hashcode of the both object should be same.

    // this is generated by IDE
    @Override
    public int hashCode() {
        int hash = 7;
        hash = 29 * hash + Objects.hashCode(this.model);
        hash = 29 * hash + this.price;
        return hash;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj) {
            return true;
        }
        if (obj == null) {
            return false;
        }
        if (getClass() != obj.getClass()) {
            return false;
        }
        final Laptop other = (Laptop) obj;
        if (this.price != other.price) {
            return false;
        }
        return Objects.equals(this.model, other.model);
    }




}


public class ObjectToString {
    
    public static void main(String[] args) {
        
        Laptop obj1=new Laptop();
        obj1.model="Lenovo ThinkPad";
        obj1.price=1000;
        Laptop obj2=new Laptop();
        obj2.model="Lenovo ThinkPad";
        obj2.price=1000;

        // System.out.println(obj1.toString());
        // if we dont mention toString() method here it is called by default even if we don't define it in Class.

        // boolean result = obj1==obj2;
        boolean result = obj1.equals(obj2);

        System.out.println(result);

    }

}
